### PR TITLE
Ask for backports

### LINKED ISSUE #156: Strict mode aka. confirm "no backport needed"
So if there was no "/backport to …" nor "/backport no" the bot should asks:

```
Is a backport needed?
if no, you can prevent this message in the future by leaving a `/backport no` comment.
```

### PR DESCRIPTION
**Pull request by nickvergessen**
I'm not sure if configs for repositories are possible.
But if so it would make sense to allow that to be optional

Fix #156

### CODE REVIEW

**Comment by skjnldsv** [comment]
This seems a bit too much no?
There is no specific settings per repo as far as I know. If we switch to a dedicated github action for this we might be able to create a config there though

**Comment by nickvergessen** [comment]
> This seems a bit too much no?

For default yes, but in talk I'd rather like to be asked if something is okay to skip, because (especially in the current days) most fixes require backporting and the few features as false-positives are okay for me. Maybe we can have 2 backport bots? Or is that per org?

**Comment by skjnldsv** [comment]
> Or is that per org?

This is per org currently Is this really that big of an issue? DO you have to request that many backports?

**Comment by nickvergessen** [comment]
I'll just leave this here: https://github.com/nextcloud/spreed/milestone/49?closed=1

**Pull request closed without merging**
